import './globals.css';
import { Open_Sans } from 'next/font/google';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const openSans = Open_Sans({ subsets: ['latin'] });

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' className={openSans.className}>
      <body className='w-full max-w-screen-2xl overflow-auto mx-auto'>
        <main>{children}</main>
      </body>
    </html>
  );
}
